# Copyright 2022 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions.triggermesh.io/v1alpha1
kind: Function
metadata:
  name: inline-python-function
spec:
  runtime: python
  responseIsEvent: true
  adapterOverrides:
    public: true
  ceOverrides:
    extensions:
      type: io.triggermesh.python.sample
  entrypoint: endpoint
  code: |
    from random import randrange

    def endpoint(event, context):
      val = randrange(10)
      if (val % 2) == 0:
        result = {
          "type" : "io.triggermesh.klr.even",
          "datacontenttype" : "application/json",
          "data" : {
            "value" : val
          }
        }

      else:
        result = {
          "type" : "io.triggermesh.klr.odd",
          "datacontenttype" : "application/json",
          "data" : {
            "value" : val
          }
        }
      return result
