/*
Copyright 2022 TriggerMesh Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"context"

	"k8s.io/apimachinery/pkg/runtime/schema"

	"knative.dev/pkg/apis"
	duckv1 "knative.dev/pkg/apis/duck/v1"

	"github.com/triggermesh/triggermesh/pkg/apis/common/v1alpha1"
	"github.com/triggermesh/triggermesh/pkg/apis/sources"
)

// Supported event types
const (
	AzureServiceBusGenericEventType = "message"
)

// GetEventTypes returns the event types generated by the source.
func (s *AzureServiceBusQueueSource) GetEventTypes() []string {
	return []string{
		AzureEventType(sources.AzureServiceServiceBus, AzureServiceBusGenericEventType),
	}
}

// GetGroupVersionKind implements kmeta.OwnerRefable.
func (s *AzureServiceBusQueueSource) GetGroupVersionKind() schema.GroupVersionKind {
	return SchemeGroupVersion.WithKind("AzureServiceBusQueueSource")
}

// GetConditionSet implements duckv1.KRShaped.
func (s *AzureServiceBusQueueSource) GetConditionSet() apis.ConditionSet {
	return v1alpha1.EventSenderConditionSet
}

// GetStatus implements duckv1.KRShaped.
func (s *AzureServiceBusQueueSource) GetStatus() *duckv1.Status {
	return &s.Status.Status
}

// GetSink implements EventSender.
func (s *AzureServiceBusQueueSource) GetSink() *duckv1.Destination {
	return &s.Spec.Sink
}

// GetStatusManager implements Reconcilable.
func (s *AzureServiceBusQueueSource) GetStatusManager() *v1alpha1.StatusManager {
	return &v1alpha1.StatusManager{
		ConditionSet: s.GetConditionSet(),
		Status:       &s.Status,
	}
}

// AsEventSource implements EventSource.
func (s *AzureServiceBusQueueSource) AsEventSource() string {
	return s.Spec.QueueID.String()
}

// GetAdapterOverrides implements AdapterConfigurable.
func (s *AzureServiceBusQueueSource) GetAdapterOverrides() *v1alpha1.AdapterOverrides {
	return s.Spec.AdapterOverrides
}

// SetDefaults implements apis.Defaultable
func (s *AzureServiceBusQueueSource) SetDefaults(ctx context.Context) {
}

// Validate implements apis.Validatable
func (s *AzureServiceBusQueueSource) Validate(ctx context.Context) *apis.FieldError {
	return nil
}
