# The Confluent target adapter requires cgo (CGO_ENABLED=1) and compiles to a
# dynamic binary with a dependency on glibc.
baseImageOverrides:
  github.com/triggermesh/triggermesh/cmd/confluenttarget-adapter: gcr.io/distroless/base:nonroot
  github.com/triggermesh/triggermesh/cmd/xslttransform-adapter: gcr.io/triggermesh/debian-libxml:v0.1.0

builds:
- id: confluenttarget-adapter
  main: ./cmd/confluenttarget-adapter
  env:
  - CGO_ENABLED=1
- id: xslttransform-adapter
  main: ./cmd/xslttransform-adapter
  env:
  - CGO_ENABLED=1
