# The Confluent target adapter requires cgo (CGO_ENABLED=1) and compiles to a
# dynamic binary with a dependency on glibc.
baseImageOverrides:
  github.com/triggermesh/triggermesh/cmd/confluenttarget-adapter: gcr.io/distroless/base:nonroot

builds:
- id: confluenttarget-adapter
  main: ./cmd/confluenttarget-adapter
  env:
  - CGO_ENABLED=1
