# Copyright 2022 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: targets.triggermesh.io/v1alpha1
kind: AzureSentinelTarget
metadata:
  name: hello-sentinel
spec:
  # subscriptionID refers to the Azure Subscription ID that the Azure Sentinel instance is associated with.
  subscriptionID: <subscription_id>
  # resourceGroup refers to the resource group where the Azure Sentinel instance is deployed.
  resourceGroup: <resource_group>
  # workspace refers to the workspace name in Azure Sentinel.
  workspace: <workspace>
  auth:
    servicePrincipal:
      tenantID:
        valueFromSecret:
          name: azure
          key: tenantID
      clientID:
        valueFromSecret:
          name: azure
          key: clientID
      clientSecret:
        valueFromSecret:
          name: azure
          key: clientSecret
