# Copyright 2022 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Example curl command to make the sample work:
# kubectl exec -ti curl -- curl -v 'http://xslttransform-demo.default.svc.cluster.local' \
#   -H 'Ce-Specversion: 1.0' \
#   -H 'Ce-Type: io.triggermesh.xslt.transform' \
#   -H 'Ce-Source: curl.shell' \
#   -H 'Content-Type: application/json' \
#   -H 'Ce-Id: 1234-abcd' \
#   -d '{
#   "xml": "<guitars><guitar><brand>Framus</brand><model>AK 1974</model><year>2012</year></guitar><guitar><brand>Fender</brand><model>Jaguar</model><year>2010</year></guitar><guitar><brand>Haar</brand><model>Telecaster</model><year>2019</year></guitar><guitar><brand>Hohner</brand><model>L75</model><year>1992</year></guitar></guitars>",
#   "xslt": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\"><xsl:template match=\"/\"><output><xsl:for-each select=\"guitars/guitar\"><xsl:sort select=\"year\"/><item><xsl:value-of select=\"year\"/><xsl:text> </xsl:text><xsl:value-of select=\"brand\"/><xsl:text> </xsl:text><xsl:value-of select=\"model\"/></item></xsl:for-each></output></xsl:template></xsl:stylesheet>"
# }
# '

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
spec:
  containers:
  - image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
    name: curl
    stdin: true
    tty: true
