# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureeventhubstargets.targets.triggermesh.io
  labels:
    eventing.knative.dev/target: 'true'
    duck.knative.dev/target: 'true'
    knative.dev/crd-install: 'true'
    triggermesh.io/crd-install: 'true'
  annotations:

spec:
  group: targets.triggermesh.io
  scope: Namespaced
  names:
    kind: AzureEventHubsTarget
    plural: azureeventhubstargets
    categories:
    - all
    - knative
    - eventing
    - targets
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: TriggerMesh event target for Azure Event Hubs.
        type: object
        properties:
          spec:
            description: Desired state of the event target.
            type: object
            properties:
              eventHubID:
                description: |-
                  Resource ID of the Event Hubs instance.

                  The expected format is
                    /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventHub/namespaces/{namespaceName}/eventhubs/{eventHubName}
                type: string
                pattern: ^\/subscriptions\/[a-z0-9-]+\/resourceGroups\/[\w.()-]+\/providers\/Microsoft.EventHub\/namespaces\/[A-Za-z0-9-]{6,50}\/event[Hh]ubs\/[a-zA-Z0-9][\w.-]{0,49}$
              auth:
                description: Authentication method to interact with the Azure Event Hubs REST API.
                type: object
                properties:
                  sasToken:
                    description: An Azure shared access signature (SAS) token. For more information about SAS tokens,
                      please refer to the Azure Storage documentation at
                      https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview.
                    type: object
                    properties:
                      keyName:
                        description: Name of the key used by the SAS token. Mutually exclusive with 'connectionString'.
                        type: object
                        properties:
                          value:
                            description: Literal name of the key.
                            type: string
                          valueFromSecret:
                            description: A reference to a Kubernetes Secret object containing the key's name.
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                            required:
                            - name
                            - key
                        oneOf:
                        - required: [value]
                        - required: [valueFromSecret]
                      keyValue:
                        description: Value of the key used by the SAS token. Mutually exclusive with 'connectionString'.
                        type: object
                        properties:
                          value:
                            description: Literal value of the key.
                            type: string
                          valueFromSecret:
                            description: A reference to a Kubernetes Secret object containing the key's value.
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                            required:
                            - name
                            - key
                        oneOf:
                        - required: [value]
                        - required: [valueFromSecret]
                      connectionString:
                        description: Connection string containing both the resource URI of the Event Hubs instance, and
                          the SAS token. Mutually exclusive with 'keyName' and 'keyValue'.
                        type: object
                        properties:
                          value:
                            description: Literal value of the connection string.
                            type: string
                          valueFromSecret:
                            description: A reference to a Kubernetes Secret object containing the connection string.
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                            required:
                            - name
                            - key
                        oneOf:
                        - required: [value]
                        - required: [valueFromSecret]
                    oneOf:
                    - required:
                      - keyName
                      - keyValue
                    - required:
                      - connectionString
                  servicePrincipal:
                    description: Credentials of an Azure Service Principal. For more information about service
                      principals, please refer to the Azure Active Directory documentation at
                      https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals.
                    type: object
                    properties:
                      tenantID:
                        description: ID of the Azure Active Directory tenant.
                        type: object
                        properties:
                          value:
                            description: Literal value of the tenant ID.
                            type: string
                            format: guid
                            pattern: ^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$
                          valueFromSecret:
                            description: A reference to a Kubernetes Secret object containing the tenant ID.
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                            required:
                            - name
                            - key
                        oneOf:
                        - required: [value]
                        - required: [valueFromSecret]
                      clientID:
                        description: ID of the registered client/application.
                        type: object
                        properties:
                          value:
                            description: Literal value of the client ID.
                            type: string
                            format: guid
                            pattern: ^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$
                          valueFromSecret:
                            description: A reference to a Kubernetes Secret object containing the client ID.
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                            required:
                            - name
                            - key
                        oneOf:
                        - required: [value]
                        - required: [valueFromSecret]
                      clientSecret:
                        description: Secret associated with the registered client/application.
                        type: object
                        properties:
                          value:
                            description: Literal value of the client secret.
                            type: string
                            format: password
                          valueFromSecret:
                            description: A reference to a Kubernetes Secret object containing the client secret.
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                            required:
                            - name
                            - key
                        oneOf:
                        - required: [value]
                        - required: [valueFromSecret]
                    required:
                    - tenantID
                    - clientID
                    - clientSecret
                oneOf:
                - required: [sasToken]
                - required: [servicePrincipal]
            required:
            - eventHubID
            - auth
          status:
            description: Reported status of the event target.
            type: object
            properties:
              observedGeneration:
                type: integer
                format: int64
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ['True', 'False', Unknown]
                    severity:
                      type: string
                      enum: [Error, Warning, Info]
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                  required:
                  - type
                  - status
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=='Ready')].status
    - name: Reason
      type: string
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
