# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sendgridtargets.targets.triggermesh.io
  labels:
    knative.dev/crd-install: 'true'
    triggermesh.io/crd-install: 'true'
    duck.knative.dev/addressable: 'true'
  annotations:
    registry.triggermesh.io/acceptedEventTypes: |
      [
        { "type": "io.triggermesh.sendgrid.email.send" }
      ]
    registry.knative.dev/eventTypes: |
      [
        { "type": "io.triggermesh.sendgrid.email.send.response" }
      ]
spec:
  group: targets.triggermesh.io
  names:
    kind: SendGridTarget
    plural: sendgridtargets
    categories:
    - all
    - knative
    - eventing
    - targets
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        description: TriggerMesh event target for Sendgrid.
        properties:
          spec:
            type: object
            description: Desired state of event target.
            properties:
              defaultFromName:
                description: Default name to use for the from field when sending email via Sendgrid.
                type: string
              defaultToName:
                description: Default name to use for the to field when sending email via Sendgrid.
                type: string
              defaultToEmail:
                description: Default email address to send mail to via Sendgrid.
                type: string
              defaultFromEmail:
                description: Default sender email address for sending mail via Sendgrid.
                type: string
              defaultSubject:
                description: Default subject to use for email sent via this target
                type: string
              defaultMessage:
                description: Default message to use for all email sent via this target.
                type: string
              apiKey:
                description: The Sendgrid API key used to authenticate access.
                type: object
                properties:
                  secretKeyRef:
                    type: object
                    properties:
                      key:
                        type: string
                      name:
                        type: string
              eventOptions:
                type: object
                description: 'When should this target generate a response event for processing: always, on error, or
                  never.'
                properties:
                  payloadPolicy:
                    type: string
                    enum: [always, error, never]
            required:
            - apiKey
          status:
            type: object
            description: Reported status of the event target.
            properties:
              acceptedEventTypes:
                type: array
                items:
                  type: string
              ceAttributes:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    source:
                      type: string
                  required:
                  - type
                  - source
              observedGeneration:
                type: integer
                format: int64
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ['True', 'False', Unknown]
                    severity:
                      type: string
                      enum: [Error, Warning, Info]
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                  required:
                  - type
                  - status
              address:
                type: object
                properties:
                  url:
                    type: string
    additionalPrinterColumns:
    - name: URL
      type: string
      jsonPath: .status.url
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=='Ready')].status
    - name: Reason
      type: string
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
