# Copyright 2023 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sample SolaceTarget object.
#
# For a list and description of all available attributes, execute the following command against a cluster where this
# Custom Resource Definition has been registered:
#
#   kubectl explain solacetargets.targets.triggermesh.io

apiVersion: targets.triggermesh.io/v1alpha1
kind: SolaceTarget
metadata:
  name: sample
spec:
  url: amqp://192.168.1.1:5672
  queueName: test
  auth:
    saslEnable: true
    username:
      valueFromSecret:
        name: solace-secret
        key: username
    password:
      valueFromSecret:
        name: solace-secret
        key: password
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
