/*
Copyright 2021 TriggerMesh Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package targets

// IntegrationTarget is implemented by types which are integration targets.
//
// An integration target:
// * processes tasks derived from events, not direct events produced by sources.
// * expects data to be in certain format (writing differentiated code for every possible event type isn't possible).
// * turns data into synchronous API calls which result in an immediate success or failure.
//
type IntegrationTarget interface {
	// AcceptedEventTypes returns the event types accepted by the target.
	AcceptedEventTypes() []string
}

// EventSource is implemented by types that emit events.
type EventSource interface {
	// GetEventTypes returns the event types generated by the source.
	GetEventTypes() []string
	// AsEventSource returns a unique reference to the source suitable for
	// use as a CloudEvent source attribute.
	AsEventSource() string
}
